INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (1, 'Kitchen', 0.26, 0, 22.5, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (2, 'Kitchen', 0.53, 1, 24.1, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (3, 'Kitchen changed', 0.2, 0, 21.5, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (4, 'Kitchen', 0.33, 1, 22.8, 4);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (5, 'Bedroom', 0.14, 1, 22.1, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (6, 'Bedroom', 0.8, 0, 23.3, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (7, 'Bedroom', 0.32, 1, 21.1, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (8, 'Bedroom', 0.56, 1, 21.1, 4);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (9, 'Living Room', 0.44, 1, 21.1, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (10, 'Living Room', 0.34, 1, 21.1, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (11, 'Living Room', 0.21, 1, 21.1, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (12, 'Living Room', 0.34, 0, 21.1, 4);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (13, 'Bathroom', 0, 1, 21.1, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (14, 'Bathroom', 0.98, 1, 21.1, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (15, 'Bathroom', 0.56, 1, 21.1, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (16, 'Bathroom', 0.11, 0, 21.1, 4);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (17, 'Dining Room', 0.86, 1, 21.1, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (18, 'Dining Room', 0.91, 0, 21.1, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (19, 'Dining Room', 0.39, 1, 21.1, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (20, 'Dining Room', 0.11, 1, 21.1, 4);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (21, 'Office', 0.25, 0, 21.1, 1);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (22, 'Office', 0.54, 0, 21.1, 2);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (23, 'Office', 0.77, 1, 21.1, 3);
INSERT INTO smarthome.rooms (id, name, brightness, light, temperature, house_id) VALUES (24, 'Office', 0.6, 0, 21.1, 4);
